### PR TITLE
Add detail about the booking system to the proposal

### PR DESCRIPTION
**Pull request by farif1**

### CODE REVIEW

**Comment by antheagonzalez** [comment]
Are we not giving them the option of paying cash at the theatre?

**Comment by antheagonzalez** [comment]
If not then gucci :)

**Comment by smartinez78** [comment]
I think we should keep it to credit/debit card since its for online ticket purchases. Also you used 'than' instead of 'then' multiple times in the description.

**Comment by farif1** [comment]
I will fix that right now

**Comment by farif1** [comment]
just fixed it.

**Comment by antheagonzalez** [comment]
gucci

**Comment by ghost** [comment]
Gucci

**Comment by smartinez78** [comment]
Gucci!

**Pull request merged**
