### PR TITLE
Lint and validate html and css files

### PR DESCRIPTION
**Pull request by smartinez78**
The booking/index.html file is flagged in a few places by the html validator, now sure how to fix those.

### CODE REVIEW

**Comment by farif1** [comment]
Gucci!!

**Comment by antheagonzalez** [comment]
gucci

**Comment by smartinez78** [comment]
Validator: [](https://validator.w3.org/#validate_by_input)
The issue appears to be with nesting ordered lists within an ordered list.

**Comment by farif1** [comment]
I'm going to let this one merge and than try to figure out how to fix that specific linter error.

**Comment by ghost** [comment]
Sounds Gucci Fizza!

**Pull request merged**
