### PR TITLE
Add all the gist of html

### PR DESCRIPTION
**Pull request by farif1**

### CODE REVIEW

**Comment by zfleckhawk** [comment]
Gucci

**Comment by ghost** [comment]
Whoops! Not Gucci. I *think* were missing the final </ul>, but maybe I’m misreading it on my phone.

**Comment by smartinez78** [comment]
I ran the files through a validator, the index.html file is showing a couple of errors.
**To view**: [https://validator.w3.org/nu/#l80c14](url)
You have a 'ul' tag that isn't closed (line 26), and it's showing an error with a 'section' tag.

**Comment by farif1** [comment]
Sorry guys for not taking my own advice about running files through the validators and linters before pushing. Thanks for checking Sofia, just fixed it.

**Comment by smartinez78** [comment]
It's alright, it happens, that's why we're working together! It all looks good to me now, gucci!

**Comment by antheagonzalez** [comment]
Gucci

**Pull request merged**
