### PR TITLE
I'm having trouble with the form so someone please merge and fix it, thanks

### PR DESCRIPTION
**Pull request by farif1**

### CODE REVIEW

**Comment by smartinez78** [comment]
Is there a specific part of the form you're having trouble with?

**Comment by farif1** [comment]
drop down menus, so for the location, I have three locations they can pick and I did that but when I see it on the browser using http-server, it looks wierd, it's not a dropdown menu

**Comment by farif1** [comment]
just fixed it guys, i was writing the code wrong. Take a look and let me know

**Comment by smartinez78** [comment]
Ran the files you modified through the validator, a few things are being flagged.

**On the Booking/index.html file:** 
Validator: [https://validator.w3.org/nu/#textarea](url)

It says that the 'date' input type isn't supported in all browsers, I'm concerned that this will mean that some people won't be able to use the form at all. Can we discuss a potential workaround? 

There's also a couple of attributes that aren't allowed on line 26, the validator offers some explanation.

**Comment by antheagonzalez** [comment]
looks gucci now!

**Comment by farif1** [comment]
Hey guys, I just fixed the validator errors, also I don't know how to get an alternative for date and time so I just used the input type text for date, time and seats for now because the validator doesn't allow it to be without it. We can change it once we have an alternative

**Comment by smartinez78** [comment]
We can ask for suggestions on that, thanks for making the changes!!! Gucci

**Comment by ghost** [comment]
Fantastic! Gucci!

**Pull request merged**
